import unittest, time
from selenium import webdriver


class NutritionAid(unittest.TestCase):
    def setUp(self):
        # create a new Chrome session
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(30)
        self.driver.maximize_window()
        # navigate to the application home page
        self.driver.get("https://nutri-aid.000webhostapp.com/")

    def test_nutriaid(self):
        #test the home button
        home_link = self.driver.find_element_by_link_text('Home')
        home_link.click()
        self.driver.implicitly_wait(3000)
        #test the about button
        about_link = self.driver.find_element_by_link_text('About')
        about_link.click()
        time.sleep(5)
        # test the sign up form
        signup_link = self.driver.find_element_by_link_text('Sign Up')
        signup_link.click()
        time.sleep(5)
        signupNameInput = self.driver.find_element_by_id("nameInput")
        signupEmailInput = self.driver.find_element_by_id("emailInput")
        signupPasswordInput = self.driver.find_element_by_id("passwordInput")
        signupConfirmPasswordInput = self.driver.find_element_by_id("confirmPasswordInput")
        signupQuestion1Input = self.driver.find_element_by_id("q1")
        signupAnswer1Input = self.driver.find_element_by_id("a1Input")
        signupQuestion2Input = self.driver.find_element_by_id("q2")
        signupAnswer2Input = self.driver.find_element_by_id("a2Input")
        signupSubmitButton = self.driver.find_element_by_id("submitbutton")
        time.sleep(5)
        signupNameInput.clear()
        signupNameInput.send_keys("aaa")
        time.sleep(5)
        signupEmailInput.clear()
        signupEmailInput.send_keys("ppp@gmail.com")
        time.sleep(5)
        signupPasswordInput.clear()
        signupPasswordInput.send_keys("aaaaaaa")
        time.sleep(5)
        signupConfirmPasswordInput.clear()
        signupConfirmPasswordInput.send_keys("aaaaaaa")
        time.sleep(5)
        signupQuestion1Input.send_keys("What is your father's middle name?")
        time.sleep(5)
        signupAnswer1Input.clear()
        signupAnswer1Input.send_keys("rrr")
        time.sleep(5)
        signupQuestion2Input.send_keys("What city were you born in?")
        time.sleep(5)
        signupAnswer2Input.clear()
        signupAnswer2Input.send_keys("www")
        time.sleep(5)
        signupSubmitButton.click()
        time.sleep(5)
        #test the initial form
        carb_Amount = self.driver.find_element_by_id("carbohydratesAmount")
        carb_Amount.clear()
        carb_Amount.send_keys("30")
        time.sleep(5)
        protein_Amount = self.driver.find_element_by_id("proteinAmount")
        protein_Amount.clear()
        protein_Amount.send_keys("10")
        time.sleep(5)
        fat_Amount = self.driver.find_element_by_id("fatAmount")
        fat_Amount.clear()
        fat_Amount.send_keys("40")
        time.sleep(5)
        calories_Amount = self.driver.find_element_by_id("caloriesAmount")
        calories_Amount.clear()
        calories_Amount.send_keys("70")
        time.sleep(5)
        sugar_Amount = self.driver.find_element_by_id("sugarAmount")
        sugar_Amount.clear()
        sugar_Amount.send_keys("90")
        time.sleep(5)
        starch_Amount = self.driver.find_element_by_id("starchAmount")
        starch_Amount.clear()
        starch_Amount.send_keys("20")
        time.sleep(5)
        glucose_Amount = self.driver.find_element_by_id("glucoseAmount")
        glucose_Amount.clear()
        glucose_Amount.send_keys("50")
        time.sleep(5)
        iron_Amount = self.driver.find_element_by_id("ironAmount")
        iron_Amount.clear()
        iron_Amount.send_keys("60")
        time.sleep(5)
        calcium_Amount = self.driver.find_element_by_id("calciumAmount")
        calcium_Amount.clear()
        calcium_Amount.send_keys("30")
        time.sleep(5)
        water_Amount = self.driver.find_element_by_id("waterAmount")
        water_Amount.clear()
        water_Amount.send_keys("30")
        time.sleep(5)
        surveyConfirmButton = self.driver.find_element_by_id("confirmbutton")
        surveyConfirmButton.click()
        time.sleep(5)
        sign_out = self.driver.find_element_by_link_text('Sign Out')
        sign_out.click()
        time.sleep(5)
        # test the signin form
        sign_in = self.driver.find_element_by_link_text('Sign In')
        sign_in.click()
        time.sleep(5)
        signinEmailInput = self.driver.find_element_by_id("signinEmailInput")
        signinPasswordInput = self.driver.find_element_by_id("signinPasswordInput")
        signinSubmitButton = self.driver.find_element_by_id("signinSubmitButton")
        signinEmailInput.clear()
        signinEmailInput.send_keys("123@gmail.com")
        time.sleep(5)
        signinPasswordInput.clear()
        signinPasswordInput.send_keys("1234abcd")
        time.sleep(5)
        signinSubmitButton.click()
        # sign_out = self.driver.find_element_by_link_text('Sign Out')
        # self.assertTrue(sign_out)
        time.sleep(5)

    # def test_search(self):
        # test the search functionality
        search_link = self.driver.find_element_by_id('searchInput')
        search_link.click()
        self.driver.implicitly_wait(1000)
        search_input = self.driver.find_element_by_id('searchInput')
        searchButton = self.driver.find_element_by_id('searchInputbutton')
        search_input.clear()
        search_input.send_keys("apple")
        time.sleep(5)
        searchButton.click()
        time.sleep(5)
        searchNextPage = self.driver.find_element_by_id('searchResults_next')
        searchNextPage.click()
        time.sleep(5)
        searchPreviousPage = self.driver.find_element_by_id('searchResults_previous')
        searchPreviousPage.click()
        time.sleep(5)

    # def test_dashboard(self):
    #     # get the options like home, about, sign in, sign up
    #     sign_in = self.driver.find_element_by_link_text('Sign In')
    #     sign_in.click()
    #     self.driver.implicitly_wait(1000)
    #     signinEmailInput = self.driver.find_element_by_id("signinEmailInput")
    #     signinPasswordInput = self.driver.find_element_by_id("signinPasswordInput")
    #     signinSubmitButton = self.driver.find_element_by_id("signinSubmitButton")
    #     signinEmailInput.clear()
    #     signinEmailInput.send_keys("123@gmail.com")
    #     time.sleep(5)
    #     signinPasswordInput.clear()
    #     signinPasswordInput.send_keys("1234abcd")
    #     time.sleep(5)
    #     signinSubmitButton.click()
    #     time.sleep(5)
        #test the dashboard functionality
        dashboard_link = self.driver.find_element_by_link_text('Dashboard')
        dashboard_link.click()
        self.driver.implicitly_wait(5)
        #test the recommended products
        dashboardRecommendations= self.driver.find_element_by_link_text('Recommended Products')
        dashboardRecommendations.click()
        time.sleep(5)
        # add some products to favorites
        addFavorites1 = self.driver.find_element_by_id("favoriteIcon-Mulberries")
        addFavorites1.click()
        time.sleep(5)
        addFavorites2 = self.driver.find_element_by_id("favoriteIcon-Melon")
        addFavorites2.click()
        time.sleep(5)
        #test the statistics functionality
        dashboardStatistics = self.driver.find_element_by_link_text('Statistics')
        dashboardStatistics.click()
        time.sleep(5)
        #test the favorites functionality
        dashboardFavorites = self.driver.find_element_by_link_text('My Favorites')
        dashboardFavorites.click()
        time.sleep(5)
        #remove some foods from favorites
        removeFavorites1 = self.driver.find_element_by_id("favListIcon0")
        removeFavorites1.click()
        time.sleep(5)



if __name__ == '__main__':
    unittest.main()
